### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by joshwizzy** [SumeetMoray/Nearby-Shops-Admin-App#1]
app/src/main/java 
org/nearbyshops/serviceprovider/DaggerComponentBuilder.java |  
error: cannot find symbol class DaggerNetComponent |  
org/nearbyshops/serviceprovider/ShopAdminList/EditShopAdmin/EditShopAdminFragment.java |  
error: cannot find symbol class ShopAdmin |  
error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code. |  
org/nearbyshops/serviceprovider/ShopAdminList/Fragment/FragmentShopAdmins.java |  
error: cannot find symbol class ShopAdmin |  
error: cannot find symbol class ShopAdmin |  
error: cannot find symbol class ShopAdmin |  
org/nearbyshops/serviceprovider/RetrofitRESTContract/ShopAdminService.java |  
error: cannot find symbol class ShopAdmin |  
error: cannot find symbol class ShopAdmin |  
error: cannot find symbol class ShopAdmin |  
org/nearbyshops/serviceprovider/ShopAdminList/Fragment/Adapter.java |  
error: cannot find symbol class ShopAdmin |  
error: cannot find symbol class ShopAdmin |  
org/nearbyshops/serviceprovider/ModelRoles/Endpoints/ShopAdminEndPoint.java |  
error: cannot find symbol class ShopAdmin |  
error: cannot find symbol class ShopAdmin |  
org/nearbyshops/serviceprovider/ShopAdminList/SlidingLayerSort/SlidingLayerSortShopAdmin.java |  
error: cannot find symbol class ShopAdmin |  
org/nearbyshops/serviceprovider/ShopAdminList/UtilityShopAdmin.java |  
error: cannot find symbol class ShopAdmin |  
org/nearbyshops/serviceprovider/DaggerComponents/NetComponent.java |  
error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code. |

**Comment by SumeetMoray** [comment]
Thanks for posting this issue. Yes there was an error. The class file was not added to github repository. 

I have updated the code and added the missing class file. Please download the new updated code and compile again !

And if any problem comes you let me know !

**Comment by joshwizzy** [comment]
The project now compiles successfully. 
Thank you.

**Comment by SumeetMoray** [comment]
If you face any further issues, you need any help with anything technical ... feel free to contact !

**Comment by maaudrana** [comment]
Screenshot link is broken pls fix it and how can i download the app?

**Comment by maaudrana** [comment]
@SumeetMoray 🤚

**Comment by SumeetMoray** [comment]
Hi ... forum is better way to connect for general questions ... https://forum.nearbyshops.org/
For downloading apps visit : https://nearbyshops.org
For downloading admin app check this link : https://developer.nearbyshops.org/installation/downloads.html
